# Generated by Django 4.2.18 on 2025-03-16 06:05

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_verified',
            new_name='_is_verified',
        ),
    ]
