# Generated by Django 4.2.18 on 2025-03-16 06:09

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_is_verified_customuser__is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='_is_verified',
            new_name='_is_otp_verified',
        ),
    ]
