# Generated by Django 4.2.18 on 2025-04-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_customuser__is_otp_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default='unknown', max_length=30),
        ),
    ]
