# Generated by Django 4.2.18 on 2025-04-24 15:07

from django.db import migrations
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_customuser_display_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', game.models.CustomUserManager()),
            ],
        ),
    ]
